-- =====================================================
-- Migration: Cheque photo upload for manual payments
-- Date: 2026-04-15
--
-- CONTEXT:
-- The manual payment modal (`ManualPaymentDialog.tsx`) lets owners log a
-- cheque payment. We now allow them to attach an optional photo of the
-- physical cheque (e.g. taken from the mobile camera via
-- `<input capture="environment">`). The photo is stored privately and
-- accessed through signed URLs generated by an API route that validates
-- ownership.
--
-- CHANGES:
-- 1. Add `payments.cheque_photo_path TEXT NULL` to store the storage path
--    of the uploaded cheque image (e.g. `cheques/<invoice_id>/<ts>.jpg`).
-- 2. Create a private `payment-proofs` storage bucket with a 5 MB file
--    size limit and a restricted list of image MIME types.
-- 3. Lock RLS on `storage.objects` for this bucket: neither anonymous
--    nor authenticated users can INSERT/SELECT directly. All access is
--    mediated by API routes using the service role key, which both
--    bypasses RLS and performs application-level ownership checks
--    (pattern used throughout the app — see `api/inspections/[iid]/photos`).
--
-- NOTE:
-- The photo is OPTIONAL. An upload failure must never block the payment
-- from being recorded (the JS layer catches upload errors and logs them).
-- =====================================================

BEGIN;

-- ============================================
-- 1. payments.cheque_photo_path column
-- ============================================

ALTER TABLE public.payments
  ADD COLUMN IF NOT EXISTS cheque_photo_path TEXT NULL;

COMMENT ON COLUMN public.payments.cheque_photo_path IS
  'Chemin de stockage (bucket payment-proofs) de la photo du chèque physique. NULL si aucune photo attachée.';

-- ============================================
-- 2. Private storage bucket for payment proofs
-- ============================================
--
-- `public = false` → tout accès passe par des URLs signées générées côté
-- serveur après vérification d'autorisation. 5 MB limit aligné avec le
-- front (voir `ManualPaymentDialog.tsx`).

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'payment-proofs',
  'payment-proofs',
  false,
  5242880, -- 5 MB
  ARRAY['image/jpeg', 'image/jpg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
)
ON CONFLICT (id) DO UPDATE
SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- ============================================
-- 3. RLS — no direct client access to this bucket
-- ============================================
--
-- Volontairement pas de policy permissive : tous les accès (upload,
-- download, delete) transitent par les routes API qui utilisent le
-- service_role client. Cela évite de devoir encoder l'owner dans le
-- path et centralise la vérification d'autorisation (lien facture → bail
-- → owner_id → profile).

DROP POLICY IF EXISTS "payment_proofs_block_anon" ON storage.objects;
DROP POLICY IF EXISTS "payment_proofs_block_auth" ON storage.objects;

-- ============================================
-- 4. Reload PostgREST schema cache
-- ============================================

NOTIFY pgrst, 'reload schema';

COMMIT;
